package minecraft

import (
	"bytes"
	"strings"
)

// ServerProperties is a map of server props
type ServerProperties map[string]string

// ParseServerProps returns a ServerProperties object that contains the parsed props
func ParseServerProps(buf []byte) ServerProperties {
	props := make(ServerProperties, 0)

	lines := bytes.Split(buf, []byte("\n"))
	for _, bLine := range lines {
		line := string(bLine)

		// skip comments
		if strings.HasPrefix(line, "#") {
			continue
		}
		// key = value
		comp := strings.Split(line, "=")
		key := comp[0]
		value := ""

		if key == "" {
			continue
		}

		if len(comp) == 2 {
			value = comp[1]
		}
		props[key] = value
	}
	return props
}

// String returns ServerProperties as a string (config file)
func (s *ServerProperties) String() string {
	config := strings.Builder{}
	config.WriteString("# generated by minepkg\n")
	for key, val := range *s {
		config.WriteString(key + "=" + val + "\n")
	}

	return config.String()
}
