project_name: minepkg
builds:
  - id: minepkg
    binary: minepkg
    env:
    - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
- id: minepkg
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  gitlab:
    owner: minepkg
    name: minepkg
  extra_files:
    - glob: ./dist/artifacts.json
    - glob: ./dist/metadata.json
nfpms:
  -
    # ID of the nfpm config, must be unique.
    id: default

    # Name of the package.
    package_name: minepkg

    homepage: https://minepkg.io/
    maintainer: Filip Weiss <me@fiws.net>
    description: A package manager designed to install Minecraft mods and modpacks.
    license: MIT
    formats:
      - deb
      - rpm

