name: tag release

on:
  push:
    tags:
      - '*'

jobs:
  tagBuilds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
      - name: Test
        run: go test -v ./...
      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/*
      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true
      - name: upload binaries to get.minepkg.io
        run: gsutil cp -r dist/* gs://minepkg-client/latest
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            minepkg/minepkg
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

