name: tag release

on:
  push:
    tags:
      - '*'

jobs:
  tagBuilds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup osslsigncode
        run: sudo apt-get update && sudo apt-get install -y osslsigncode
      - name: Write osslsigncode cert & key
        env:
          SIGNING_CERT: ${{ secrets.SIGNING_CERT }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          mkdir -p ./.tmp
          echo '${{ secrets.SIGNING_CERT }}' > ./.tmp/cert.cert
          echo '${{ secrets.SIGNING_KEY }}' > ./.tmp/key.pem
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.12.3
          args: release --rm-dist --debug
      - name: Delete osslsigncode cert & key
        run: rm -rf ./.tmp
      - name: Test
        run: go test -v ./...
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*
      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true
      - name: upload binaries to get.minepkg.io
        run: gsutil cp -r dist/* gs://minepkg-client/latest

